### ISSUE TITLE
Enhancement of Signup page

### ISSUE THREAD

**Issue by Avishek3223** [Avishek3223/chat-app-frontend#2]
![image](https://github.com/user-attachments/assets/0ebf8da4-e435-4a0a-85f7-93b18e40ed70)
this type of Ui should be there for small screen and large screen

**Current Ui**
![image](https://github.com/user-attachments/assets/716deaaa-e717-4631-9f14-5cd795e4f41f)

**Comment by jr-boney** [comment]
I am new to open source contribution but i can help you with that

**Comment by Avishek3223** [comment]
@jr-boney you can fork and make changes and screenshots if all working then I will accept your pull request

**Comment by jr-boney** [comment]
![Screenshot (204)](https://github.com/user-attachments/assets/23c7ecc3-8b3c-43a6-858c-2d58a949e29e)
![Screenshot (203)](https://github.com/user-attachments/assets/88724bfc-ade6-4aa2-9a54-4dd72f3780a6)

Bro How do i push my changes to which branch

**Comment by Avishek3223** [comment]
hi create an account should have confirm password also 

create a new branch 
git checkout -b signup-page

then push there and send a pull request

**Comment by jr-boney** [comment]
git push origin signup-page
remote: Permission to Avishek3223/chat-app-frontend.git denied 
to jr-boney.
fatal: unable to access 'https://github.com/Avishek3223/chat-app-frontend/': The requested URL returned error: 403
bro this error shows up

**Comment by Avishek3223** [comment]
@jr-boney bro you can't directly push to my repo. You have to fork my repo then clone in your local system make changes their and create a branch name signup and push to that repo. Open my repo in GitHub an option for pull request will be visible click on that.
